image: maven:3.8.4-openjdk-11-slim

stages:
  - build
  - test

variables:
  REPORT_FILE: "target/surefire-reports/TEST-*.xml"

build:
  stage: build
  before_script:
    -  cat /etc/os-release
  script:
    - mvn compile

test:
  stage: test
  script: bash -x test_script.sh
  artifacts:
    when: always
    reports:
      junit: $REPORT_FILE

#Job for scheduled pipeline in prod branch
test-prod-scheduled:
  stage: test
  script: bash -x test_script.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "master"'
  artifacts:
    when: always
    reports:
      junit: $REPORT_FILE

#Job for scheduled pipeline for feature branch or preproduction branch
test-develop-scheduled:
  stage: test
  script: bash -x test_script.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH=="/^(?!feature).+@/"'
  artifacts:
    when: always
    reports:
      junit: $REPORT_FILE