image: maven:3.8.4-openjdk-11-slim

stages:
  - build
  - test

build:
  stage: build
  before_script:
    -  cat /etc/os-release
  script: mvn compile

test:
  stage: test
  script: bash -x test_script.sh